jobs:
  ignore-test:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "filter ignore"
  only-test:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "filter only"

workflows:
  version: 2
  pr-test:
    jobs:
      - ignore-test:
          filters:
            branches:
              ignore:
                - /feature\/.*/
  build:
    jobs:
      - only-test:
          filters:
            branches:
              only:
                - /feature\/.*/
